### ISSUE TITLE
[MSHADE-467] Dependency-reduced POM with missing exclusions in concurrent build

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-shade-plugin#721]
**[Alexander Kriegisch](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kriegaex)** opened **[MSHADE-467](https://issues.apache.org/jira/browse/MSHADE-467?redirect=false)** and commented

As discussed in [this maven-users thread](https://lists.apache.org/thread/ljdbh9h0lqs1qsf9o8bnm35mtr85y4vr), when running Maven builds for [this reproducer](https://github.com/stl543/shadeMT) concurrently, some dependency exclusions are missing from the generated dependency-reduced POMs. Run the reproducer like this:

```none
$ mvn clean package -T 4 | grep 'BUILD SUCCESS' && find . -name "dependency-reduced-pom.xml" -exec bash -c 'cat $0 | grep exclu | wc -l ' {} \;
[INFO] BUILD SUCCESS
12
12
12
12
```

When running with `-T 1`, however, the correct result is 20.

This concurrency issue might have been introduced by the MSHADE-413 fix, but I am not sure.

I have a local fix, synchronising on the injected mojo parameter `MavenSession session`  in the lower section of `ShadeMojo::rewriteDependencyReducedPomIfWeHaveReduction`. There might be a better way to fix the problem, but I it leave that up to the PR reviewers to come up with one, if any.

---

**Affects:** 3.4.1, 3.5.0, 3.5.1

**Remote Links:**
- [GitHub Pull Request #210
](https://github.com/apache/maven-shade-plugin/pull/210)

**Comment by marwin1991** [comment]
Fixed by https://github.com/apache/maven-shade-plugin/pull/770
